const complaints = {
  complaints: {
    type: "conversation.list",
    pages: {
      type: "pages",
      page: 1,
      per_page: 150,
      total_pages: 1,
    },
    total_count: 2,
    conversations: [
      {
        type: "conversation",
        id: "10",
        created_at: 1704512404,
        updated_at: 1704512809,
        waiting_since: null,
        snoozed_until: null,
        source: {
          type: "conversation",
          id: "1995588781",
          delivered_as: "customer_initiated",
          subject: "",
          body: '<p>{"comments":"complaint","catagory":"H"}</p>',
          author: {
            type: "user",
            id: "6597fc9828740179e18f3506",
            name: "Karnataka Pics",
            email: "picskarnataka@gmail.com",
          },
          attachments: [],
          url: null,
          redacted: false,
        },
        contacts: {
          type: "contact.list",
          contacts: [
            {
              type: "contact",
              id: "6597fc9828740179e18f3506",
              external_id: null,
            },
          ],
        },
        first_contact_reply: {
          created_at: 1704512404,
          type: "conversation",
          url: null,
        },
        admin_assignee_id: null,
        team_assignee_id: null,
        open: true,
        state: "open",
        read: false,
        tags: {
          type: "tag.list",
          tags: [],
        },
        priority: "not_priority",
        sla_applied: null,
        statistics: {
          type: "conversation_statistics",
          time_to_assignment: null,
          time_to_admin_reply: null,
          time_to_first_close: null,
          time_to_last_close: null,
          median_time_to_reply: null,
          first_contact_reply_at: 1704512405,
          first_assignment_at: null,
          first_admin_reply_at: 1704512809,
          first_close_at: null,
          last_assignment_at: null,
          last_assignment_admin_reply_at: null,
          last_contact_reply_at: 1704512405,
          last_admin_reply_at: 1704512809,
          last_close_at: null,
          last_closed_by_id: null,
          count_reopens: 0,
          count_assignments: 0,
          count_conversation_parts: 3,
        },
        conversation_rating: null,
        teammates: {
          type: "admin.list",
          admins: [
            {
              type: "admin",
              id: "7029657",
            },
          ],
        },
        title: "",
        custom_attributes: {
          Language: "English",
        },
        topics: {
          type: "topic.list",
          topics: [],
          total_count: 0,
        },
        ticket: null,
        linked_objects: {
          type: "list",
          data: [],
          total_count: 0,
          has_more: false,
        },
      },
    ],
  },
};

const complaint = {
  response: {
    type: "conversation",
    id: "10",
    created_at: 1704512404,
    updated_at: 1704512809,
    waiting_since: null,
    snoozed_until: null,
    source: {
      type: "conversation",
      id: "1995588781",
      delivered_as: "customer_initiated",
      subject: "",
      body: '<p>{"comments":"complaint","catagory":"H"}</p>',
      author: {
        type: "user",
        id: "6597fc9828740179e18f3506",
        name: "Karnataka Pics",
        email: "picskarnataka@gmail.com",
      },
      attachments: [],
      url: null,
      redacted: false,
    },
    contacts: {
      type: "contact.list",
      contacts: [
        {
          type: "contact",
          id: "6597fc9828740179e18f3506",
          external_id: null,
        },
      ],
    },
    first_contact_reply: {
      created_at: 1704512404,
      type: "conversation",
      url: null,
    },
    admin_assignee_id: null,
    team_assignee_id: null,
    open: true,
    state: "open",
    read: false,
    tags: {
      type: "tag.list",
      tags: [],
    },
    priority: "not_priority",
    sla_applied: null,
    statistics: {
      type: "conversation_statistics",
      time_to_assignment: null,
      time_to_admin_reply: null,
      time_to_first_close: null,
      time_to_last_close: null,
      median_time_to_reply: null,
      first_contact_reply_at: 1704512405,
      first_assignment_at: null,
      first_admin_reply_at: 1704512809,
      first_close_at: null,
      last_assignment_at: null,
      last_assignment_admin_reply_at: null,
      last_contact_reply_at: 1704512405,
      last_admin_reply_at: 1704512809,
      last_close_at: null,
      last_closed_by_id: null,
      count_reopens: 0,
      count_assignments: 0,
      count_conversation_parts: 3,
    },
    conversation_rating: null,
    teammates: {
      type: "admin.list",
      admins: [
        {
          type: "admin",
          id: "7029657",
        },
      ],
    },
    title: "",
    custom_attributes: {
      Language: "English",
    },
    topics: {
      type: "topic.list",
      topics: [],
      total_count: 0,
    },
    ticket: null,
    linked_objects: {
      type: "list",
      data: [],
      total_count: 0,
      has_more: false,
    },
    conversation_parts: {
      type: "conversation_part.list",
      conversation_parts: [
        {
          type: "conversation_part",
          id: "17",
          part_type: "conversation_attribute_updated_by_admin",
          body: null,
          created_at: 1704512405,
          updated_at: 1704512405,
          notified_at: 1704512405,
          assigned_to: null,
          author: {
            id: "7029658",
            type: "bot",
            name: "Fin",
            email: "operator+aphd867j@intercom.io",
          },
          attachments: [],
          external_id: null,
          redacted: false,
        },
        {
          type: "conversation_part",
          id: "18",
          part_type: "comment",
          body: '<p class="no-margin">Hey</p>',
          created_at: 1704512809,
          updated_at: 1704512809,
          notified_at: 1704512809,
          assigned_to: null,
          author: {
            id: "7029657",
            type: "admin",
            name: "Aalasyam Sai varshith",
            email: "saivarshith3041@gmail.com",
          },
          attachments: [],
          external_id: null,
          redacted: false,
        },
      ],
      total_count: 2,
    },
  },
};

const user = {
  existingUser: {
    type: "list",
    data: [
      {
        type: "contact",
        id: "6597fc9828740179e18f3506",
        workspace_id: "aphd867j",
        external_id: null,
        role: "user",
        email: "picskarnataka@gmail.com",
        phone: null,
        name: "Karnataka Pics",
        avatar: null,
        owner_id: null,
        social_profiles: {
          type: "list",
          data: [],
        },
        has_hard_bounced: false,
        marked_email_as_spam: false,
        unsubscribed_from_emails: false,
        created_at: 1704459416,
        updated_at: 1704514193,
        signed_up_at: null,
        last_seen_at: null,
        last_replied_at: 1704514192,
        last_contacted_at: 1704512990,
        last_email_opened_at: null,
        last_email_clicked_at: null,
        language_override: null,
        browser: null,
        browser_version: null,
        browser_language: null,
        os: null,
        location: {
          type: "location",
          country: null,
          region: null,
          city: null,
          country_code: null,
          continent_code: null,
        },
        android_app_name: null,
        android_app_version: null,
        android_device: null,
        android_os_version: null,
        android_sdk_version: null,
        android_last_seen_at: null,
        ios_app_name: null,
        ios_app_version: null,
        ios_device: null,
        ios_os_version: null,
        ios_sdk_version: null,
        ios_last_seen_at: null,
        custom_attributes: {},
        tags: {
          type: "list",
          data: [],
          url: "/contacts/6597fc9828740179e18f3506/tags",
          total_count: 0,
          has_more: false,
        },
        notes: {
          type: "list",
          data: [],
          url: "/contacts/6597fc9828740179e18f3506/notes",
          total_count: 0,
          has_more: false,
        },
        companies: {
          type: "list",
          data: [],
          url: "/contacts/6597fc9828740179e18f3506/companies",
          total_count: 0,
          has_more: false,
        },
        opted_out_subscription_types: {
          type: "list",
          data: [],
          url: "/contacts/6597fc9828740179e18f3506/subscriptions",
          total_count: 0,
          has_more: false,
        },
        opted_in_subscription_types: {
          type: "list",
          data: [],
          url: "/contacts/6597fc9828740179e18f3506/subscriptions",
          total_count: 0,
          has_more: false,
        },
        utm_campaign: null,
        utm_content: null,
        utm_medium: null,
        utm_source: null,
        utm_term: null,
        referrer: null,
        sms_consent: false,
        unsubscribed_from_sms: false,
      },
    ],
    total_count: 1,
    pages: {
      type: "pages",
      page: 1,
      per_page: 50,
      total_pages: 1,
    },
  },
};

exports.user = user;
exports.complaints = complaints;
exports.complaint = complaint;
